"""
email_sender.py — Sends the daily crypto recommendation as a formatted HTML email via Gmail SMTP
"""
import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
import re

logger = logging.getLogger(__name__)

# Maps recommendation keywords to visual styles
BADGE_STYLES = {
    "BUY":  ("🟢 BUY",  "#16a34a", "#dcfce7"),
    "HOLD": ("🟡 HOLD", "#b45309", "#fef9c3"),
    "SELL": ("🔴 SELL", "#dc2626", "#fee2e2"),
}

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Daily Crypto Recommendation</title>
</head>
<body style="margin:0;padding:0;background:#0f172a;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0f172a;padding:32px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#1e293b;border-radius:16px;overflow:hidden;box-shadow:0 8px 32px rgba(0,0,0,0.4);">

        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#6366f1,#8b5cf6,#a855f7);padding:32px 40px;text-align:center;">
            <div style="font-size:36px;margin-bottom:8px;">📊</div>
            <h1 style="margin:0;color:#fff;font-size:24px;font-weight:700;letter-spacing:-0.5px;">Daily Crypto Recommendation</h1>
            <p style="margin:8px 0 0;color:rgba(255,255,255,0.8);font-size:14px;">{date}</p>
          </td>
        </tr>

        <!-- Body -->
        <tr>
          <td style="padding:32px 40px;">
            {coin_sections}
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="padding:20px 40px 32px;border-top:1px solid #334155;">
            <p style="margin:0;color:#64748b;font-size:12px;text-align:center;line-height:1.6;">
              ⚠️ <strong style="color:#94a3b8;">Not financial advice.</strong> This report is AI-generated for informational purposes only.<br/>
              Always do your own research before making investment decisions.<br/>
              <span style="color:#475569;">Generated by Crypto AI Agent • {date}</span>
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>
"""

COIN_SECTION_TEMPLATE = """\
<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;background:#0f172a;border-radius:12px;overflow:hidden;border:1px solid #334155;">
  <tr>
    <td style="padding:20px 24px;background:#162032;border-bottom:1px solid #334155;">
      <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
          <td><h2 style="margin:0;color:#f1f5f9;font-size:20px;font-weight:700;">₿ {coin}</h2></td>
          <td align="right">
            <span style="display:inline-block;padding:6px 16px;border-radius:20px;font-size:14px;font-weight:700;color:{badge_color};background:{badge_bg};">{badge_label}</span>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td style="padding:20px 24px;">
      <div style="color:#cbd5e1;font-size:14px;line-height:1.8;white-space:pre-line;">{analysis}</div>
    </td>
  </tr>
</table>
"""


def markdown_to_plain(text: str) -> str:
    """Strip markdown bold/headers for use in HTML pre-line blocks."""
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'#{1,4}\s*', '', text)
    text = re.sub(r'-{3,}', '', text)
    return text.strip()


def extract_recommendation(coin_text: str) -> str:
    """Detect BUY/HOLD/SELL from the coin's recommendation block."""
    upper = coin_text.upper()
    if "BUY" in upper:
        return "BUY"
    elif "SELL" in upper:
        return "SELL"
    return "HOLD"


def build_html_email(coins: list[str], recommendation_text: str, date_str: str) -> str:
    """Parse the AI recommendation text and build the HTML email."""
    # Split recommendation block per coin using ## headers
    sections = re.split(r'##\s+', recommendation_text)
    coin_blocks = {}
    for section in sections:
        if not section.strip():
            continue
        lines = section.strip().split('\n', 1)
        if lines:
            first_line = lines[0].strip().upper()
            content = lines[1].strip() if len(lines) > 1 else ""
            # Try to match a coin name
            for coin in coins:
                if str(first_line).find(coin.upper()) != -1:
                    coin_blocks[coin] = content
                    break

    coin_sections_html = ""
    for coin in coins:
        content = coin_blocks.get(coin, "Analysis not available for this coin in this run.")
        rec = extract_recommendation(content)
        label, color, bg = BADGE_STYLES.get(rec, ("🟡 HOLD", "#b45309", "#fef9c3"))
        plain_content = markdown_to_plain(content)
        coin_sections_html += COIN_SECTION_TEMPLATE.format(
            coin=coin,
            badge_label=label,
            badge_color=color,
            badge_bg=bg,
            analysis=plain_content,
        )

    return HTML_TEMPLATE.format(date=date_str, coin_sections=coin_sections_html)


def send_email(
    smtp_email: str,
    smtp_password: str,
    recipient_email: str,
    coins: list[str],
    recommendation_text: str,
) -> bool:
    """
    Build and send the HTML email report.
    Returns True on success, False on failure.
    """
    date_str = datetime.now().strftime("%A, %B %d, %Y")
    subject = f"📊 Daily Crypto Recommendation — {datetime.now().strftime('%b %d, %Y')}"

    html_body = build_html_email(coins, recommendation_text, date_str)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_email
    msg["To"] = recipient_email

    # Plain text fallback
    plain = f"Daily Crypto Recommendation — {date_str}\n\n{recommendation_text}"
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    try:
        logger.info(f"Connecting to Gmail SMTP...")
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(smtp_email, smtp_password)
            server.sendmail(smtp_email, recipient_email, msg.as_string())
        logger.info(f"✅ Email sent successfully to {recipient_email}")
        return True
    except smtplib.SMTPAuthenticationError:
        logger.error("❌ SMTP Authentication failed. Check your SMTP_EMAIL and SMTP_APP_PASSWORD in .env")
        return False
    except Exception as e:
        logger.error(f"❌ Failed to send email: {e}")
        return False


if __name__ == "__main__":
    from config import get_config
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    config = get_config()
    test_recommendation = """
## XRP
**Recommendation:** HOLD
**Confidence:** Medium
**Sentiment:** Neutral

**Key Signals:**
- Recent regulatory news shows mixed signals
- Trading volume slightly above average
- No major partnerships announced recently

**Action for Today:**
XRP is showing consolidation near current levels. Consider holding existing positions while monitoring regulatory developments closely. Avoid adding new positions until clarity improves.

**Risk Level:** Medium
**Timeframe:** Short-term (1-7 days)

---

## Ethereum
**Recommendation:** BUY
**Confidence:** High
**Sentiment:** Bullish

**Key Signals:**
- ETH ETF inflows reported this week
- Network activity at record highs
- Developer ecosystem activity growing

**Action for Today:**
Strong on-chain signals and institutional interest suggest buying pressure. Consider a small accumulation position with a stop-loss below recent support.

**Risk Level:** Low
**Timeframe:** Short-term (1-7 days)
"""
    print("Sending test email...")
    success = send_email(
        smtp_email=config["SMTP_EMAIL"],
        smtp_password=config["SMTP_APP_PASSWORD"],
        recipient_email=config["RECIPIENT_EMAIL"],
        coins=config["COINS"],
        recommendation_text=test_recommendation,
    )
    if success:
        print(f"✅ Test email sent to {config['RECIPIENT_EMAIL']}")
    else:
        print("❌ Test email failed. Check your .env settings.")
